import mediapipe as mp

mp_pose = mp.solutions.pose
lmPose = mp_pose.PoseLandmark

# Thresholds
VISIBILITY_THRESHOLD = 0.5

# Pose mappings
POSE_CONNECTIONS = {
  "nose": 0,
  "left_eye_inner": 1,
  "left_eye": 2,
  "left_eye_outer": 3,
  "right_eye_inner": 4,
  "right_eye": 5,
  "right_eye_outer": 6,
  "left_ear": 7,
  "right_ear": 8,
  "mouth_left": 9,
  "mouth_right": 10,
  "left_shoulder": 11,
  "right_shoulder": 12,
  "left_elbow": 13,
  "right_elbow": 14,
  "left_wrist": 15,
  "right_wrist": 16,
  "left_pinky": 17,
  "right_pinky": 18,
  "left_index": 19,
  "right_index": 20,
  "left_thumb": 21,
  "right_thumb": 22,
  "left_hip": 23,
  "right_hip": 24,
  "left_knee": 25,
  "right_knee": 26,
  "left_ankle": 27,
  "right_ankle": 28,
  "left_heel": 29,
  "right_heel": 30,
  "left_foot_index": 31,
  "right_foot_index": 32,
}

NORM_POSE_CONNECTIONS = {
  "nose": lmPose.NOSE,
  "left_eye_inner": lmPose.LEFT_EYE_INNER,
  "left_eye": lmPose.LEFT_EYE,
  "left_eye_outer": lmPose.LEFT_EYE_OUTER,
  "right_eye_inner": lmPose.RIGHT_EYE_INNER,
  "right_eye": lmPose.RIGHT_EYE,
  "right_eye_outer": lmPose.RIGHT_EYE_OUTER,
  "left_ear": lmPose.LEFT_EAR,
  "right_ear": lmPose.RIGHT_EAR,
  "mouth_left": lmPose.MOUTH_LEFT,
  "mouth_right": lmPose.MOUTH_RIGHT,
  "left_shoulder": lmPose.LEFT_SHOULDER,
  "right_shoulder": lmPose.RIGHT_SHOULDER,
  "left_elbow": lmPose.LEFT_ELBOW,
  "right_elbow": lmPose.RIGHT_ELBOW,
  "left_wrist": lmPose.LEFT_WRIST,
  "right_wrist": lmPose.RIGHT_WRIST,
  "left_pinky": lmPose.LEFT_PINKY,
  "right_pinky": lmPose.RIGHT_PINKY,
  "left_index": lmPose.LEFT_INDEX,
  "right_index": lmPose.RIGHT_INDEX,
  "left_thumb": lmPose.LEFT_THUMB,
  "right_thumb": lmPose.RIGHT_THUMB,
  "left_hip": lmPose.LEFT_HIP,
  "right_hip": lmPose.RIGHT_HIP,
  "left_knee": lmPose.LEFT_KNEE,
  "right_knee": lmPose.RIGHT_KNEE,
  "left_ankle": lmPose.LEFT_ANKLE,
  "right_ankle": lmPose.RIGHT_ANKLE,
  "left_heel": lmPose.LEFT_HEEL,
  "right_heel": lmPose.RIGHT_HEEL,
  "left_foot_index": lmPose.LEFT_FOOT_INDEX,
  "right_foot_index": lmPose.RIGHT_FOOT_INDEX,
}